import React from 'react';
import { useDispatch, useSelector } from 'react-redux';
import classes from './Counter.module.css';
import { counterActions } from '../store';

const Counter = () => {
  const dispatch = useDispatch();
  const counter = useSelector(state => state.counter);
  const showCounter = useSelector(state => state.showCounter);

  const incrementHandler = () => {
    // dispatch({type: "increment"});
    dispatch(counterActions.increment()); // increment() when executed creates an action object with type set to a unique action identifier
    // action object generated by redux: {type: SOME_UNIQUE_IDENTIFIER}
  };

  const increaseHandler = () => {
    // dispatch({type: "increase", amount: 5});
    dispatch(counterActions.increase(5)); // anything can be passed as payload.
    // action object generated by redux: {type: SOME_UNIQUE_IDENTIFIER, payload: 5}
  };

  const decrementhandler = () => {
    // dispatch({type: "decrement"});
    dispatch(counterActions.decrement());
  };

  const toggleCounterHandler = () => {
    // dispatch({type: "toggle"});
    dispatch(counterActions.toggleCounter());
  };

  return (
    <main className={classes.counter}>
      <h1>Redux Counter</h1>
      {showCounter && <div className={classes.value}>{counter}</div>}
      <div>
        <button onClick={incrementHandler}>Increment</button>
        <button onClick={increaseHandler}>Increment by 5</button>
        <button onClick={decrementhandler}>Decrement</button>
      </div>
      <button onClick={toggleCounterHandler}>Toggle Counter</button>
    </main>
  );
};

export default Counter;
